Test begin
=========================================================
;
;
Number of collapsed edges: 0
;
Number of collapsed edges: 0
=========================================================
a;
a;
Number of collapsed edges: 0
a;
Number of collapsed edges: 0
=========================================================
(a:1,b:1);
(a:1,b:1);
Number of collapsed edges: 0
(a:1,b:1);
Number of collapsed edges: 0
=========================================================
(a:0,b:0);
(a:0,b:0);
Number of collapsed edges: 0
(a:0,b:0);
Number of collapsed edges: 0
=========================================================
(a:1,b:1,c:1);
(a:1,b:1,c:1);
Number of collapsed edges: 0
(a:1,b:1,c:1);
Number of collapsed edges: 0
=========================================================
(a:0,b:1,c:1);
(a:0,b:1,c:1);
Number of collapsed edges: 0
(a:0,b:1,c:1);
Number of collapsed edges: 0
=========================================================
(a:1,b:0,c:1);
(a:1,b:0,c:1);
Number of collapsed edges: 0
(a:1,b:0,c:1);
Number of collapsed edges: 0
=========================================================
(a:1,b:1,c:0);
(a:1,b:1,c:0);
Number of collapsed edges: 0
(a:1,b:1,c:0);
Number of collapsed edges: 0
=========================================================
(a:-1,b:-1,c:-1);
(a:0,b:0,c:0);
Number of collapsed edges: 0
(a:0,b:0,c:0);
Number of collapsed edges: 0
=========================================================
(a:1,b:1,(c:1,d:1):1);
(a:1,b:1,(c:1,d:1):1);
Number of collapsed edges: 0
(a:1,b:1,(c:1,d:1):1);
Number of collapsed edges: 0
=========================================================
(a:0,b:1,(c:1,d:1):1);
(a:0,b:1,(c:1,d:1):1);
Number of collapsed edges: 0
(a:0,b:1,(c:1,d:1):1);
Number of collapsed edges: 0
=========================================================
(a:1,b:0,(c:1,d:1):1);
(a:1,b:0,(c:1,d:1):1);
Number of collapsed edges: 0
(a:1,b:0,(c:1,d:1):1);
Number of collapsed edges: 0
=========================================================
(a:1,b:1,(c:0,d:1):1);
(a:1,b:1,(c:0,d:1):1);
Number of collapsed edges: 0
(a:1,b:1,(c:0,d:1):1);
Number of collapsed edges: 0
=========================================================
(a:1,b:1,(c:1,d:0):1);
(a:1,b:1,(c:1,d:0):1);
Number of collapsed edges: 0
(a:1,b:1,(c:1,d:0):1);
Number of collapsed edges: 0
=========================================================
(a:1,b:1,(c:1,d:1):0);
(a:1,b:1,c:1,d:1);
Number of collapsed edges: 1
(a:1,b:1,c:1,d:1);
Number of collapsed edges: 1
=========================================================
(a:1,b:1,(c:1,d:1):-1);
(a:1,b:1,c:1,d:1);
Number of collapsed edges: 1
(a:1,b:1,c:1,d:1);
Number of collapsed edges: 1
=========================================================
(a:1,b:1,(c:1,(d:1,e:1):1):1);
(a:1,b:1,(c:1,(d:1,e:1):1):1);
Number of collapsed edges: 0
(a:1,b:1,(c:1,(d:1,e:1):1):1);
Number of collapsed edges: 0
=========================================================
(a:1,b:1,(c:1,(d:1,e:1):0):1);
(a:1,b:1,(c:1,d:1,e:1):1);
Number of collapsed edges: 1
(a:1,b:1,(c:1,d:1,e:1):1);
Number of collapsed edges: 1
=========================================================
(a:1,b:1,(c:1,(d:1,e:1):1):0);
(a:1,b:1,c:1,(d:1,e:1):1);
Number of collapsed edges: 1
(a:1,b:1,c:1,(d:1,e:1):1);
Number of collapsed edges: 1
=========================================================
(a:1,b:1,(c:1,(d:1,e:1):0):0);
(a:1,b:1,c:1,d:1,e:1);
Number of collapsed edges: 2
(a:1,b:1,c:1,d:1,e:1);
Number of collapsed edges: 2
=========================================================
(a:1,b:1,(c:1,d:1,e:1):1);
(a:1,b:1,(c:1,d:1,e:1):1);
Number of collapsed edges: 0
(a:1,b:1,(c:1,d:1,e:1):1);
Number of collapsed edges: 0
=========================================================
(a:1,b:1,(c:1,d:1,e:1):0);
(a:1,b:1,c:1,d:1,e:1);
Number of collapsed edges: 1
(a:1,b:1,c:1,d:1,e:1);
Number of collapsed edges: 1
=========================================================
(a:-1,b:-1,(c:-1,d:-1,e:-1):-1);
(a:0,b:0,c:0,d:0,e:0);
Number of collapsed edges: 1
(a:0,b:0,c:0,d:0,e:0);
Number of collapsed edges: 1
=========================================================
Test end
