Test begin
1 1 1 1 1 1
>one
ACGTGG
>two
ACGTGG
>three
ACTTGT
1 1 1 2 1
>one
ACGGT
>two
ACGGT
>three
ACGTT

>one
>two
>three
1 1 1 1
>one
----
>two
----
>three
----
1 1 1 1 1 1 1 1 1 1 1
>one
aACGTGtGkK-
>two
aAcGTGtGyYN
>three
aACTTGtTSsn
1 2 1 1 2 2 2
>one
-ACGGKT
>two
NACGGYT
>three
NACGTST
1 2
>one
-M
>two
NR
>three
NS
1 2 1 1 1 1
>one
-M----
>two
NR----
>three
NS----
1 1 1 1 1 1 1 1 1 1 1
>one
TTTTTTTTTTT
>two
ttttttttttt
>three
TtTtTtTtTtT
11
>one
T
>two
T
>three
T

>one
>two
>three
1 1 1 1
>one
----
>two
----
>three
----
1 1 1 1 1 1 1 1 1 1 1 1
>one
AaCtYKBVacGT
>two
AACtYKATcaAA
>three
CcGcRHATcAaa
>four
CCGCRHATcAaA
2 1 1 1 1 1 1 1 1 1 1
>one
AABCCGKTTVY
>two
ACAACAKATTY
>three
CCAAGAHACTR
>four
CCAAGAHACTR
4 1 1 2
>one
AMMV
>two
AMMT
>three
CDKT
>four
CDKT
4 1 1 2 1 1 1 1
>one
AMMV----
>two
AMMT----
>three
CDKT----
>four
CDKT----
Test end
