Test begin
# Basic
1 1 1 1 1 1
>one
ACGTGG
>two
ACGTGG
>three
ACTTGT
# Compact
1 1 1 2 1
>one
ACGGT
>two
ACGGT
>three
ACGTT
# Fitch compact

>one
>two
>three
# Fitch compact plus pad
1 1 1 1
>one
----
>two
----
>three
----
# Basic
1 1 1 1 1 1 1 1 1 1 1
>one
aACGTGtGkK-
>two
aAcGTGtGyYN
>three
aACTTGtTSsn
# Compact
1 2 1 1 2 2 2
>one
-ACGGKT
>two
NACGGYT
>three
NACGTST
# Fitch compact
1 2
>one
-M
>two
NS
>three
NR
# Fitch compact plus pad
1 2 1 1 1 1
>one
-M----
>two
NS----
>three
NR----
# Basic
1 1 1 1 1 1 1 1 1 1 1
>one
TTTTTTTTTTT
>two
ttttttttttt
>three
TtTtTtTtTtT
# Compact
11
>one
T
>two
T
>three
T
# Fitch compact

>one
>two
>three
# Fitch compact plus pad
1 1 1 1
>one
----
>two
----
>three
----
# Basic
1 1 1 1 1 1 1 1 1 1 1 1
>one
AaCtYKBVacGT
>two
AACtYKATcaAA
>three
CcGcRHATcAaa
>four
CCGCRHATcAaA
# Compact
2 1 1 1 1 1 1 1 1 1 1
>one
AABCCGKTTVY
>two
ACAACAKATTY
>three
CCAAGAHACTR
>four
CCAAGAHACTR
# Fitch compact
4 1 1 2
>one
AMMV
>two
AMMT
>three
CBKT
>four
CBKT
# Fitch compact plus pad
4 1 1 2 1 1 1 1
>one
AMMV----
>two
AMMT----
>three
CBKT----
>four
CBKT----
Test end
