Test begin
=== '>Label\nNXVHMDRWABSYCKGT-\n' ===
>Label
NXVHMDRWABSYCKGT-
=== '>Label\nA C\nGT' ===
>Label
ACGT
=== '>Taxon_A\nACGT-\n>Taxon_B\nACG-T\n' ===
>Taxon_A
ACGT-
>Taxon_B
ACG-T
=== '>Taxon_A This is a comment.\nACGT-\n>Taxon_B\tThis is another comment.\nACG-T\n' ===
>Taxon_A
ACGT-
>Taxon_B
ACG-T
=== '>\n' ===
Exception <class 'Fasta.SyntaxError'>: Line 1: Invalid token
=== '> Comment\n' ===
Exception <class 'Fasta.SyntaxError'>: Line 1: Invalid token
=== '>Label\n' ===
Exception <class 'Parsing.SyntaxError'>: Unexpected token: <$>
=== '>Label\nACGTZ\n' ===
Exception <class 'Fasta.SyntaxError'>: Line 2: Invalid token
=== '>Taxon_A\n>Taxon_B\nACGT\n' ===
Exception <class 'Parsing.SyntaxError'>: Unexpected token: descr ('>Taxon_B')
=== '>Taxon_A\nACGT>Taxon_B\nACGT\n' ===
Exception <class 'Fasta.SyntaxError'>: Line 2: Invalid token
=== '>Taxon_A\nACGT\n>Taxon_B\n' ===
Exception <class 'Parsing.SyntaxError'>: Unexpected token: <$>
=== '>Label\nABCDEFGHIKLMNPQRSTUVWXYZ-\n' ===
>Label
ABCDEFGHIKLMNPQRSTUVWXYZ-
=== '>Label\nABCDEFGHIJKLMN\n' ===
Exception <class 'Fasta.SyntaxError'>: Line 2: Invalid token
=== '>Label\nABCDE789FGHIK\n' ===
Exception <class 'Fasta.SyntaxError'>: Line 2: Invalid token
Test end
