Test begin
===========================================================
Neighbors held: all
===========================================================
Initial tree has score 16220
0
  Neighbors: 9266156
  Trees held: 9266156
  Score of chosen neighbor: 16264
1
  Neighbors: 10264000
  Trees held: 10264000
  Score of chosen neighbor: 16306
2
  Neighbors: 11149428
  Trees held: 11149428
  Score of chosen neighbor: 16411
3
  Neighbors: 13279508
  Trees held: 13279508
  Score of chosen neighbor: 16508
4
  Neighbors: 13604244
  Trees held: 13604244
  Score of chosen neighbor: 16565
===========================================================
Initial tree has score 37800
0
  Neighbors: 16986856
  Trees held: 16986856
  Score of chosen neighbor: 37801
1
  Neighbors: 17316760
  Trees held: 17316760
  Score of chosen neighbor: 37802
2
  Neighbors: 17573520
  Trees held: 17573520
  Score of chosen neighbor: 37804
3
  Neighbors: 17572816
  Trees held: 17572816
  Score of chosen neighbor: 37803
4
  Neighbors: 18222204
  Trees held: 18222204
  Score of chosen neighbor: 37809
===========================================================
Initial tree has score 16590
0
  Neighbors: 8522180
  Trees held: 8522180
  Score of chosen neighbor: 16625
1
  Neighbors: 8539296
  Trees held: 8539296
  Score of chosen neighbor: 16723
2
  Neighbors: 8746288
  Trees held: 8746288
  Score of chosen neighbor: 16792
3
  Neighbors: 11142804
  Trees held: 11142804
  Score of chosen neighbor: 16849
4
  Neighbors: 11179492
  Trees held: 11179492
  Score of chosen neighbor: 16930
===========================================================
Initial tree has score 16645
0
  Neighbors: 7806360
  Trees held: 7806360
  Score of chosen neighbor: 16751
1
  Neighbors: 9144728
  Trees held: 9144728
  Score of chosen neighbor: 16866
2
  Neighbors: 10799668
  Trees held: 10799668
  Score of chosen neighbor: 16944
3
  Neighbors: 10800776
  Trees held: 10800776
  Score of chosen neighbor: 16961
4
  Neighbors: 11202452
  Trees held: 11202452
  Score of chosen neighbor: 16999
===========================================================
Initial tree has score 16569
0
  Neighbors: 8442732
  Trees held: 8442732
  Score of chosen neighbor: 16615
1
  Neighbors: 8298096
  Trees held: 8298096
  Score of chosen neighbor: 16782
2
  Neighbors: 8291356
  Trees held: 8291356
  Score of chosen neighbor: 16848
3
  Neighbors: 8201244
  Trees held: 8201244
  Score of chosen neighbor: 16925
4
  Neighbors: 9134180
  Trees held: 9134180
  Score of chosen neighbor: 17033
===========================================================
Neighbors held: better
===========================================================
Initial tree has score 16565
0
  Neighbors: 14043168
  Trees held: 281876
  Score of chosen neighbor: 16558
1
  Neighbors: 13703824
  Trees held: 265862
  Score of chosen neighbor: 16548
2
  Neighbors: 14912532
  Trees held: 221062
  Score of chosen neighbor: 16490
3
  Neighbors: 13466420
  Trees held: 152034
  Score of chosen neighbor: 16468
4
  Neighbors: 13170488
  Trees held: 147870
  Score of chosen neighbor: 16466
===========================================================
Initial tree has score 37809
0
  Neighbors: 22620188
  Trees held: 10446366
  Score of chosen neighbor: 37800
1
  Neighbors: 21805056
  Trees held: 9875397
  Score of chosen neighbor: 37793
2
  Neighbors: 20326820
  Trees held: 9219475
  Score of chosen neighbor: 37783
3
  Neighbors: 20372668
  Trees held: 8592962
  Score of chosen neighbor: 37764
4
  Neighbors: 19221916
  Trees held: 7545012
  Score of chosen neighbor: 37745
===========================================================
Initial tree has score 16930
0
  Neighbors: 11703848
  Trees held: 259663
  Score of chosen neighbor: 16923
1
  Neighbors: 10247676
  Trees held: 246316
  Score of chosen neighbor: 16903
2
  Neighbors: 9894624
  Trees held: 159486
  Score of chosen neighbor: 16875
3
  Neighbors: 10130680
  Trees held: 108246
  Score of chosen neighbor: 16873
4
  Neighbors: 10287636
  Trees held: 107537
  Score of chosen neighbor: 16855
===========================================================
Initial tree has score 16999
0
  Neighbors: 11207492
  Trees held: 172904
  Score of chosen neighbor: 16943
1
  Neighbors: 12371188
  Trees held: 223594
  Score of chosen neighbor: 16933
2
  Neighbors: 14143896
  Trees held: 139510
  Score of chosen neighbor: 16930
3
  Neighbors: 13406260
  Trees held: 136570
  Score of chosen neighbor: 16900
4
  Neighbors: 10770452
  Trees held: 53925
  Score of chosen neighbor: 16898
===========================================================
Initial tree has score 17033
0
  Neighbors: 9290792
  Trees held: 92869
  Score of chosen neighbor: 17020
1
  Neighbors: 9355292
  Trees held: 97315
  Score of chosen neighbor: 17009
2
  Neighbors: 8692760
  Trees held: 69553
  Score of chosen neighbor: 16998
3
  Neighbors: 9240660
  Trees held: 48230
  Score of chosen neighbor: 16982
4
  Neighbors: 9464008
  Trees held: 45434
  Score of chosen neighbor: 16946
===========================================================
Neighbors held: best
===========================================================
Initial tree has score 16466
0
  Neighbors: 12697224
  Trees held: 1
  Score of chosen neighbor: 16371
1
  Neighbors: 9949240
  Trees held: 4
  Score of chosen neighbor: 16323
2
  Neighbors: 9649104
  Trees held: 1
  Score of chosen neighbor: 16281
3
  Neighbors: 9451228
  Trees held: 1
  Score of chosen neighbor: 16239
4
  Neighbors: 9355568
  Trees held: 2
  Score of chosen neighbor: 16220
===========================================================
Initial tree has score 37745
0
  Neighbors: 21013572
  Trees held: 1
  Score of chosen neighbor: 37590
1
  Neighbors: 21014976
  Trees held: 1
  Score of chosen neighbor: 37449
2
  Neighbors: 21075020
  Trees held: 1
  Score of chosen neighbor: 37310
3
  Neighbors: 21109580
  Trees held: 1
  Score of chosen neighbor: 37174
4
  Neighbors: 21100148
  Trees held: 1
  Score of chosen neighbor: 37039
===========================================================
Initial tree has score 16855
0
  Neighbors: 10057988
  Trees held: 1
  Score of chosen neighbor: 16775
1
  Neighbors: 10122200
  Trees held: 2
  Score of chosen neighbor: 16718
2
  Neighbors: 10112916
  Trees held: 1
  Score of chosen neighbor: 16668
3
  Neighbors: 10624564
  Trees held: 4
  Score of chosen neighbor: 16619
4
  Neighbors: 10444700
  Trees held: 3
  Score of chosen neighbor: 16576
===========================================================
Initial tree has score 16898
0
  Neighbors: 12154800
  Trees held: 1
  Score of chosen neighbor: 16820
1
  Neighbors: 12165836
  Trees held: 2
  Score of chosen neighbor: 16756
2
  Neighbors: 10337072
  Trees held: 1
  Score of chosen neighbor: 16711
3
  Neighbors: 10328548
  Trees held: 1
  Score of chosen neighbor: 16675
4
  Neighbors: 10194852
  Trees held: 1
  Score of chosen neighbor: 16643
===========================================================
Initial tree has score 16946
0
  Neighbors: 9294036
  Trees held: 1
  Score of chosen neighbor: 16776
1
  Neighbors: 9309064
  Trees held: 1
  Score of chosen neighbor: 16668
2
  Neighbors: 9175580
  Trees held: 1
  Score of chosen neighbor: 16628
3
  Neighbors: 9821852
  Trees held: 4
  Score of chosen neighbor: 16596
4
  Neighbors: 9731612
  Trees held: 2
  Score of chosen neighbor: 16566
Test end
