Test begin
===========================================================
Neighbors held: all
===========================================================
Initial tree has score 16220
0
  Neighbors: 9266156
  Trees held: 9266156
  Score of chosen neighbor: 16319
1
  Neighbors: 9233320
  Trees held: 9233320
  Score of chosen neighbor: 16408
2
  Neighbors: 11093548
  Trees held: 11093548
  Score of chosen neighbor: 16485
3
  Neighbors: 11687864
  Trees held: 11687864
  Score of chosen neighbor: 16550
4
  Neighbors: 11671172
  Trees held: 11671172
  Score of chosen neighbor: 16632
===========================================================
Initial tree has score 37535
0
  Neighbors: 8117308
  Trees held: 8117308
  Score of chosen neighbor: 37541
1
  Neighbors: 8799576
  Trees held: 8799576
  Score of chosen neighbor: 37569
2
  Neighbors: 11125152
  Trees held: 11125152
  Score of chosen neighbor: 37568
3
  Neighbors: 10983240
  Trees held: 10983240
  Score of chosen neighbor: 37576
4
  Neighbors: 10966032
  Trees held: 10966032
  Score of chosen neighbor: 37575
===========================================================
Initial tree has score 16602
0
  Neighbors: 8398572
  Trees held: 8398572
  Score of chosen neighbor: 16689
1
  Neighbors: 9077556
  Trees held: 9077556
  Score of chosen neighbor: 16803
2
  Neighbors: 11183312
  Trees held: 11183312
  Score of chosen neighbor: 16878
3
  Neighbors: 11619656
  Trees held: 11619656
  Score of chosen neighbor: 16893
4
  Neighbors: 10005004
  Trees held: 10005004
  Score of chosen neighbor: 16956
===========================================================
Initial tree has score 16620
0
  Neighbors: 7833444
  Trees held: 7833444
  Score of chosen neighbor: 16732
1
  Neighbors: 8021084
  Trees held: 8021084
  Score of chosen neighbor: 16803
2
  Neighbors: 9325596
  Trees held: 9325596
  Score of chosen neighbor: 16887
3
  Neighbors: 9273816
  Trees held: 9273816
  Score of chosen neighbor: 16967
4
  Neighbors: 9259336
  Trees held: 9259336
  Score of chosen neighbor: 17082
===========================================================
Initial tree has score 16569
0
  Neighbors: 8442732
  Trees held: 8442732
  Score of chosen neighbor: 16601
1
  Neighbors: 8473724
  Trees held: 8473724
  Score of chosen neighbor: 16671
2
  Neighbors: 8429184
  Trees held: 8429184
  Score of chosen neighbor: 16768
3
  Neighbors: 8403616
  Trees held: 8403616
  Score of chosen neighbor: 16880
4
  Neighbors: 8440540
  Trees held: 8440540
  Score of chosen neighbor: 17026
===========================================================
Neighbors held: better
===========================================================
Initial tree has score 16632
0
  Neighbors: 11794500
  Trees held: 180717
  Score of chosen neighbor: 16618
1
  Neighbors: 10835488
  Trees held: 150748
  Score of chosen neighbor: 16610
2
  Neighbors: 11598172
  Trees held: 135031
  Score of chosen neighbor: 16608
3
  Neighbors: 10780460
  Trees held: 52535
  Score of chosen neighbor: 16597
4
  Neighbors: 10040144
  Trees held: 36893
  Score of chosen neighbor: 16587
===========================================================
Initial tree has score 37575
0
  Neighbors: 11186096
  Trees held: 3366147
  Score of chosen neighbor: 37574
1
  Neighbors: 11136060
  Trees held: 3385730
  Score of chosen neighbor: 37572
2
  Neighbors: 10511264
  Trees held: 3072249
  Score of chosen neighbor: 37539
3
  Neighbors: 10412680
  Trees held: 2385479
  Score of chosen neighbor: 37532
4
  Neighbors: 10635252
  Trees held: 2406994
  Score of chosen neighbor: 37528
===========================================================
Initial tree has score 16956
0
  Neighbors: 11735248
  Trees held: 225637
  Score of chosen neighbor: 16947
1
  Neighbors: 11691404
  Trees held: 200015
  Score of chosen neighbor: 16943
2
  Neighbors: 11943788
  Trees held: 170712
  Score of chosen neighbor: 16899
3
  Neighbors: 11002464
  Trees held: 121968
  Score of chosen neighbor: 16881
4
  Neighbors: 10281312
  Trees held: 30171
  Score of chosen neighbor: 16877
===========================================================
Initial tree has score 17082
0
  Neighbors: 9360604
  Trees held: 145680
  Score of chosen neighbor: 17075
1
  Neighbors: 8899624
  Trees held: 128767
  Score of chosen neighbor: 17074
2
  Neighbors: 9214800
  Trees held: 157062
  Score of chosen neighbor: 17057
3
  Neighbors: 9209476
  Trees held: 148115
  Score of chosen neighbor: 17018
4
  Neighbors: 9182796
  Trees held: 80882
  Score of chosen neighbor: 17015
===========================================================
Initial tree has score 17026
0
  Neighbors: 11076812
  Trees held: 423519
  Score of chosen neighbor: 16956
1
  Neighbors: 11006880
  Trees held: 117612
  Score of chosen neighbor: 16929
2
  Neighbors: 9772016
  Trees held: 59747
  Score of chosen neighbor: 16912
3
  Neighbors: 10370648
  Trees held: 54932
  Score of chosen neighbor: 16892
4
  Neighbors: 9301940
  Trees held: 31114
  Score of chosen neighbor: 16888
===========================================================
Neighbors held: best
===========================================================
Initial tree has score 16587
0
  Neighbors: 9963852
  Trees held: 2
  Score of chosen neighbor: 16489
1
  Neighbors: 10013588
  Trees held: 2
  Score of chosen neighbor: 16423
2
  Neighbors: 10032436
  Trees held: 2
  Score of chosen neighbor: 16364
3
  Neighbors: 9565288
  Trees held: 1
  Score of chosen neighbor: 16305
4
  Neighbors: 9598188
  Trees held: 1
  Score of chosen neighbor: 16264
===========================================================
Initial tree has score 37528
0
  Neighbors: 10533860
  Trees held: 1
  Score of chosen neighbor: 37383
1
  Neighbors: 10515448
  Trees held: 1
  Score of chosen neighbor: 37242
2
  Neighbors: 10503376
  Trees held: 1
  Score of chosen neighbor: 37106
3
  Neighbors: 10475204
  Trees held: 1
  Score of chosen neighbor: 36973
4
  Neighbors: 10478552
  Trees held: 1
  Score of chosen neighbor: 36842
===========================================================
Initial tree has score 16877
0
  Neighbors: 9899080
  Trees held: 1
  Score of chosen neighbor: 16776
1
  Neighbors: 9858344
  Trees held: 5
  Score of chosen neighbor: 16694
2
  Neighbors: 9787628
  Trees held: 2
  Score of chosen neighbor: 16628
3
  Neighbors: 9429220
  Trees held: 3
  Score of chosen neighbor: 16607
4
  Neighbors: 9323192
  Trees held: 1
  Score of chosen neighbor: 16586
===========================================================
Initial tree has score 17015
0
  Neighbors: 9092512
  Trees held: 1
  Score of chosen neighbor: 16900
1
  Neighbors: 8907020
  Trees held: 2
  Score of chosen neighbor: 16815
2
  Neighbors: 8930348
  Trees held: 1
  Score of chosen neighbor: 16732
3
  Neighbors: 8930072
  Trees held: 1
  Score of chosen neighbor: 16668
4
  Neighbors: 8590488
  Trees held: 1
  Score of chosen neighbor: 16611
===========================================================
Initial tree has score 16888
0
  Neighbors: 9494896
  Trees held: 1
  Score of chosen neighbor: 16767
1
  Neighbors: 9347360
  Trees held: 1
  Score of chosen neighbor: 16670
2
  Neighbors: 9349376
  Trees held: 1
  Score of chosen neighbor: 16598
3
  Neighbors: 9421692
  Trees held: 1
  Score of chosen neighbor: 16575
4
  Neighbors: 9090040
  Trees held: 3
  Score of chosen neighbor: 16556
Test end
