Test begin

=== '>Label\nNXVHMDRWABSYCKGT-\n' ===
--label--: 'Label'
--chars--: 'NXVHMDRWABSYCKGT-'

=== '>Label\nA C\nGT' ===
--label--: 'Label'
--chars--: 'ACGT'

=== '\n>Taxon_A\nACGT-\n>Taxon_B\nACG-T\n' ===
--label--: 'Taxon_A'
--chars--: 'ACGT-'
--label--: 'Taxon_B'
--chars--: 'ACG-T'

=== '\n>\n' ===
Exception crux.FastaParser.SyntaxError: At 2:1 (token '', char '\n'): Empty label

=== '\n>Label\n' ===
--label--: 'Label'
Exception crux.FastaParser.SyntaxError: At 3:0 (token '', char ''): Missing character data

=== '\n>Label\nACGTZ\n' ===
--label--: 'Label'
Exception crux.FastaParser.SyntaxError: At 3:4 (token 'ACGT', char 'Z'): Invalid character data

=== '\n>Taxon_A\n>Taxon_B\nACGT\n' ===
--label--: 'Taxon_A'
Exception crux.FastaParser.SyntaxError: At 3:0 (token '', char '>'): Missing character data

=== '\n>Taxon_A\nACGT>Taxon_B\nACGT\n' ===
--label--: 'Taxon_A'
Exception crux.FastaParser.SyntaxError: At 3:4 (token 'ACGT', char '>'): Invalid character data

=== '\n>Taxon_A\nACGT\n>Taxon_B\n' ===
--label--: 'Taxon_A'
--chars--: 'ACGT'
--label--: 'Taxon_B'
Exception crux.FastaParser.SyntaxError: At 5:0 (token '', char ''): Missing character data

=== '>Label\nNXVHMDRWABSYCKGT-\n' ===
--label--: 'Label'
--chars--: 'NXVHMDRWABSYCKGT-'

=== '>Label\nA C\nGT' ===
--label--: 'Label'
--chars--: 'ACGT'

=== '\n>Taxon_A\nACGT-\n>Taxon_B\nACG-T\n' ===
--label--: 'Taxon_A'
--chars--: 'ACGT-'
--label--: 'Taxon_B'
--chars--: 'ACG-T'

=== '\n>\n' ===
Exception crux.FastaParser.SyntaxError: At 2:1 (token '', char '\n'): Empty label

=== '\n>Label\n' ===
--label--: 'Label'
Exception crux.FastaParser.SyntaxError: At 3:0 (token '', char ''): Missing character data

=== '\n>Label\nACGTZ\n' ===
--label--: 'Label'
Exception crux.FastaParser.SyntaxError: At 3:4 (token 'ACGT', char 'Z'): Invalid character data

=== '\n>Taxon_A\n>Taxon_B\nACGT\n' ===
--label--: 'Taxon_A'
Exception crux.FastaParser.SyntaxError: At 3:0 (token '', char '>'): Missing character data

=== '\n>Taxon_A\nACGT>Taxon_B\nACGT\n' ===
--label--: 'Taxon_A'
Exception crux.FastaParser.SyntaxError: At 3:4 (token 'ACGT', char '>'): Invalid character data

=== '\n>Taxon_A\nACGT\n>Taxon_B\n' ===
--label--: 'Taxon_A'
--chars--: 'ACGT'
--label--: 'Taxon_B'
Exception crux.FastaParser.SyntaxError: At 5:0 (token '', char ''): Missing character data

=== '>Label\nABCDEFGHIKLMNPQRSTUVWXYZ-\n' ===
--label--: 'Label'
--chars--: 'ABCDEFGHIKLMNPQRSTUVWXYZ-'

=== '\n>Label\nABCDEFGHIJKLMN\n' ===
--label--: 'Label'
Exception crux.FastaParser.SyntaxError: At 3:9 (token 'ABCDEFGHI', char 'J'): Invalid character data

=== '\n>Label\nABCDE789FGHIK\n' ===
--label--: 'Label'
Exception crux.FastaParser.SyntaxError: At 3:5 (token 'ABCDE', char '7'): Invalid character data

=== '>Label\nABCDEFGHIKLMNPQRSTUVWXYZ-\n' ===
--label--: 'Label'
--chars--: 'ABCDEFGHIKLMNPQRSTUVWXYZ-'

=== '\n>Label\nABCDEFGHIJKLMN\n' ===
--label--: 'Label'
Exception crux.FastaParser.SyntaxError: At 3:9 (token 'ABCDEFGHI', char 'J'): Invalid character data

=== '\n>Label\nABCDE789FGHIK\n' ===
--label--: 'Label'
Exception crux.FastaParser.SyntaxError: At 3:5 (token 'ABCDE', char '7'): Invalid character data
Test end
